-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_demosaic_0_0_DebayerG is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgBayer_dout : IN STD_LOGIC_VECTOR (39 downto 0);
    imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgBayer_empty_n : IN STD_LOGIC;
    imgBayer_read : OUT STD_LOGIC;
    imgG_din : OUT STD_LOGIC_VECTOR (119 downto 0);
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_full_n : IN STD_LOGIC;
    imgG_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_read : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c9_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c9_full_n : IN STD_LOGIC;
    bayerPhase_c9_write : OUT STD_LOGIC );
end;


architecture behav of system_v_demosaic_0_0_DebayerG is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv17_1FFFE : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal bayerPhase_c9_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln274_fu_334_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln274_reg_748 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_fu_338_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal loopHeight_reg_753 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln293_1_reg_758 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln294_fu_362_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln294_reg_764 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln315_1_fu_382_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln315_1_reg_769 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor229_1_cast_fu_394_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor229_1_cast_reg_774 : STD_LOGIC_VECTOR (14 downto 0);
    signal out_y_fu_417_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal out_y_reg_782 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_fu_423_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_787 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp84_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp84_reg_792 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp170_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp170_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_lcssa5490_load_reg_802 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_lcssa54535492_load_reg_807 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54575494_load_reg_812 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54595496_load_reg_817 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54635498_load_reg_822 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54655500_load_reg_827 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54695502_load_reg_832 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54715504_load_reg_837 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54755506_load_reg_842 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54775508_load_reg_847 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_load_reg_852 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_1_load_reg_857 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_2_load_reg_862 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_4_load_reg_867 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_5_load_reg_872 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_6_load_reg_877 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_8_load_reg_882 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_9_load_reg_887 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_10_load_reg_892 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_12_load_reg_897 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_13_load_reg_902 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_14_load_reg_907 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_16_load_reg_912 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_17_load_reg_917 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_18_load_reg_922 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_load_reg_927 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_195_load_reg_932 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_196_load_reg_937 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_197_load_reg_942 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_198_load_reg_947 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp689_fu_541_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp689_reg_952 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp230_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp230_reg_957 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp230_1_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp230_1_reg_962 : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_yuv_q1 : STD_LOGIC_VECTOR (39 downto 0);
    signal linebuf_yuv_1_q1 : STD_LOGIC_VECTOR (39 downto 0);
    signal linebuf_yuv_2_q1 : STD_LOGIC_VECTOR (39 downto 0);
    signal linebuf_yuv_3_q1 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_idle : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_ready : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgBayer_read : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_din : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_write : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_d0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_d0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_d0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_we0 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_d0 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce1 : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9_ap_vld : STD_LOGIC;
    signal grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pixBuf_198_fu_204 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_197_fu_200 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_196_fu_196 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_195_fu_192 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_fu_188 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_18_fu_184 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_17_fu_180 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_16_fu_176 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_14_fu_172 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_13_fu_168 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_12_fu_164 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_10_fu_160 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_9_fu_156 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_8_fu_152 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_6_fu_148 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_5_fu_144 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_4_fu_140 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_2_fu_136 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_1_fu_132 : STD_LOGIC_VECTOR (9 downto 0);
    signal bayerWindow_fu_128 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54775508_fu_124 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54755506_fu_120 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54715504_fu_116 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54695502_fu_112 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54655500_fu_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54635498_fu_104 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54595496_fu_100 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54575494_fu_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa54535492_fu_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_lcssa5490_fu_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_84 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal y_8_fu_411_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln315_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_fu_348_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln283_fu_344_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln315_fu_366_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln_fu_372_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor229_1_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and226_cast_fu_533_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_fu_536_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgBayer_dout : IN STD_LOGIC_VECTOR (39 downto 0);
        imgBayer_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgBayer_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgBayer_empty_n : IN STD_LOGIC;
        imgBayer_read : OUT STD_LOGIC;
        imgG_din : OUT STD_LOGIC_VECTOR (119 downto 0);
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_full_n : IN STD_LOGIC;
        imgG_write : OUT STD_LOGIC;
        bayerWindow_80 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_81 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_82 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_83 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_84 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_18 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_17 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_16 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_14 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_13 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_12 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_10 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_9 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_8 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_6 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_5 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_4 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_2 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_1 : IN STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54775508 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54755506 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54715504 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54695502 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54655500 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54635498 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54595496 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54575494 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa54535492 : IN STD_LOGIC_VECTOR (9 downto 0);
        p_lcssa5490 : IN STD_LOGIC_VECTOR (9 downto 0);
        add_ln315_1 : IN STD_LOGIC_VECTOR (14 downto 0);
        out_y : IN STD_LOGIC_VECTOR (16 downto 0);
        cmp689 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp230_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp230 : IN STD_LOGIC_VECTOR (0 downto 0);
        linebuf_yuv_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_3_ce0 : OUT STD_LOGIC;
        linebuf_yuv_3_we0 : OUT STD_LOGIC;
        linebuf_yuv_3_d0 : OUT STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_3_ce1 : OUT STD_LOGIC;
        linebuf_yuv_3_q1 : IN STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_2_ce0 : OUT STD_LOGIC;
        linebuf_yuv_2_we0 : OUT STD_LOGIC;
        linebuf_yuv_2_d0 : OUT STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_2_ce1 : OUT STD_LOGIC;
        linebuf_yuv_2_q1 : IN STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_1_ce0 : OUT STD_LOGIC;
        linebuf_yuv_1_we0 : OUT STD_LOGIC;
        linebuf_yuv_1_d0 : OUT STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_1_ce1 : OUT STD_LOGIC;
        linebuf_yuv_1_q1 : IN STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_ce0 : OUT STD_LOGIC;
        linebuf_yuv_we0 : OUT STD_LOGIC;
        linebuf_yuv_d0 : OUT STD_LOGIC_VECTOR (39 downto 0);
        linebuf_yuv_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_yuv_ce1 : OUT STD_LOGIC;
        linebuf_yuv_q1 : IN STD_LOGIC_VECTOR (39 downto 0);
        zext_ln283 : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp170 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp84 : IN STD_LOGIC_VECTOR (0 downto 0);
        bayerWindow_85_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_85_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_86_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_86_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_87_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_87_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_88_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_88_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_89_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_89_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_38_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_38_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_37_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_37_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_36_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_36_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_34_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_34_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_33_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_33_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_32_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_32_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_30_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_30_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_29_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_29_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_28_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_28_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_26_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_26_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_25_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_25_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_24_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_24_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_22_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_22_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_21_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_21_out_ap_vld : OUT STD_LOGIC;
        bayerWindow_20_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        bayerWindow_20_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        p_out9 : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_out9_ap_vld : OUT STD_LOGIC );
    end component;


    component system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (39 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;



begin
    linebuf_yuv_U : component system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W
    generic map (
        DataWidth => 40,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce1,
        q1 => linebuf_yuv_q1);

    linebuf_yuv_1_U : component system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W
    generic map (
        DataWidth => 40,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce1,
        q1 => linebuf_yuv_1_q1);

    linebuf_yuv_2_U : component system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W
    generic map (
        DataWidth => 40,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce1,
        q1 => linebuf_yuv_2_q1);

    linebuf_yuv_3_U : component system_v_demosaic_0_0_DebayerG_linebuf_yuv_RAM_AUTO_1R1W
    generic map (
        DataWidth => 40,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address0,
        ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce0,
        we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_we0,
        d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_d0,
        address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address1,
        ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce1,
        q1 => linebuf_yuv_3_q1);

    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250 : component system_v_demosaic_0_0_DebayerG_Pipeline_VITIS_LOOP_318_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start,
        ap_done => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done,
        ap_idle => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_idle,
        ap_ready => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_ready,
        imgBayer_dout => imgBayer_dout,
        imgBayer_num_data_valid => ap_const_lv3_0,
        imgBayer_fifo_cap => ap_const_lv3_0,
        imgBayer_empty_n => imgBayer_empty_n,
        imgBayer_read => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgBayer_read,
        imgG_din => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_din,
        imgG_num_data_valid => ap_const_lv3_0,
        imgG_fifo_cap => ap_const_lv3_0,
        imgG_full_n => imgG_full_n,
        imgG_write => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_write,
        bayerWindow_80 => pixBuf_198_load_reg_947,
        bayerWindow_81 => pixBuf_197_load_reg_942,
        bayerWindow_82 => pixBuf_196_load_reg_937,
        bayerWindow_83 => pixBuf_195_load_reg_932,
        bayerWindow_84 => pixBuf_load_reg_927,
        bayerWindow_18 => bayerWindow_18_load_reg_922,
        bayerWindow_17 => bayerWindow_17_load_reg_917,
        bayerWindow_16 => bayerWindow_16_load_reg_912,
        bayerWindow_14 => bayerWindow_14_load_reg_907,
        bayerWindow_13 => bayerWindow_13_load_reg_902,
        bayerWindow_12 => bayerWindow_12_load_reg_897,
        bayerWindow_10 => bayerWindow_10_load_reg_892,
        bayerWindow_9 => bayerWindow_9_load_reg_887,
        bayerWindow_8 => bayerWindow_8_load_reg_882,
        bayerWindow_6 => bayerWindow_6_load_reg_877,
        bayerWindow_5 => bayerWindow_5_load_reg_872,
        bayerWindow_4 => bayerWindow_4_load_reg_867,
        bayerWindow_2 => bayerWindow_2_load_reg_862,
        bayerWindow_1 => bayerWindow_1_load_reg_857,
        bayerWindow => bayerWindow_load_reg_852,
        p_lcssa54775508 => p_lcssa54775508_load_reg_847,
        p_lcssa54755506 => p_lcssa54755506_load_reg_842,
        p_lcssa54715504 => p_lcssa54715504_load_reg_837,
        p_lcssa54695502 => p_lcssa54695502_load_reg_832,
        p_lcssa54655500 => p_lcssa54655500_load_reg_827,
        p_lcssa54635498 => p_lcssa54635498_load_reg_822,
        p_lcssa54595496 => p_lcssa54595496_load_reg_817,
        p_lcssa54575494 => p_lcssa54575494_load_reg_812,
        p_lcssa54535492 => p_lcssa54535492_load_reg_807,
        p_lcssa5490 => p_lcssa5490_load_reg_802,
        add_ln315_1 => add_ln315_1_reg_769,
        out_y => out_y_reg_782,
        cmp689 => cmp689_reg_952,
        cmp230_1 => cmp230_1_reg_962,
        cmp230 => cmp230_reg_957,
        linebuf_yuv_3_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address0,
        linebuf_yuv_3_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce0,
        linebuf_yuv_3_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_we0,
        linebuf_yuv_3_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_d0,
        linebuf_yuv_3_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_address1,
        linebuf_yuv_3_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_3_ce1,
        linebuf_yuv_3_q1 => linebuf_yuv_3_q1,
        linebuf_yuv_2_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address0,
        linebuf_yuv_2_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce0,
        linebuf_yuv_2_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_we0,
        linebuf_yuv_2_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_d0,
        linebuf_yuv_2_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_address1,
        linebuf_yuv_2_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_2_ce1,
        linebuf_yuv_2_q1 => linebuf_yuv_2_q1,
        linebuf_yuv_1_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address0,
        linebuf_yuv_1_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce0,
        linebuf_yuv_1_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_we0,
        linebuf_yuv_1_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_d0,
        linebuf_yuv_1_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_address1,
        linebuf_yuv_1_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_1_ce1,
        linebuf_yuv_1_q1 => linebuf_yuv_1_q1,
        linebuf_yuv_address0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address0,
        linebuf_yuv_ce0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce0,
        linebuf_yuv_we0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_we0,
        linebuf_yuv_d0 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_d0,
        linebuf_yuv_address1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_address1,
        linebuf_yuv_ce1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_linebuf_yuv_ce1,
        linebuf_yuv_q1 => linebuf_yuv_q1,
        zext_ln283 => width,
        cmp170 => cmp170_reg_797,
        cmp84 => cmp84_reg_792,
        bayerWindow_85_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out,
        bayerWindow_85_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out_ap_vld,
        bayerWindow_86_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out,
        bayerWindow_86_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out_ap_vld,
        bayerWindow_87_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out,
        bayerWindow_87_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out_ap_vld,
        bayerWindow_88_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out,
        bayerWindow_88_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out_ap_vld,
        bayerWindow_89_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out,
        bayerWindow_89_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out_ap_vld,
        bayerWindow_38_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out,
        bayerWindow_38_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out_ap_vld,
        bayerWindow_37_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out,
        bayerWindow_37_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out_ap_vld,
        bayerWindow_36_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out,
        bayerWindow_36_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out_ap_vld,
        bayerWindow_34_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out,
        bayerWindow_34_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out_ap_vld,
        bayerWindow_33_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out,
        bayerWindow_33_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out_ap_vld,
        bayerWindow_32_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out,
        bayerWindow_32_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out_ap_vld,
        bayerWindow_30_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out,
        bayerWindow_30_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out_ap_vld,
        bayerWindow_29_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out,
        bayerWindow_29_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out_ap_vld,
        bayerWindow_28_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out,
        bayerWindow_28_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out_ap_vld,
        bayerWindow_26_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out,
        bayerWindow_26_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out_ap_vld,
        bayerWindow_25_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out,
        bayerWindow_25_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out_ap_vld,
        bayerWindow_24_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out,
        bayerWindow_24_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out_ap_vld,
        bayerWindow_22_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out,
        bayerWindow_22_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out_ap_vld,
        bayerWindow_21_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out,
        bayerWindow_21_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out_ap_vld,
        bayerWindow_20_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out,
        bayerWindow_20_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out_ap_vld,
        p_out => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out,
        p_out_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out_ap_vld,
        p_out1 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1,
        p_out1_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1_ap_vld,
        p_out2 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2,
        p_out2_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2_ap_vld,
        p_out3 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3,
        p_out3_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3_ap_vld,
        p_out4 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4,
        p_out4_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4_ap_vld,
        p_out5 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5,
        p_out5_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5_ap_vld,
        p_out6 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6,
        p_out6_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6_ap_vld,
        p_out7 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7,
        p_out7_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7_ap_vld,
        p_out8 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8,
        p_out8_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8_ap_vld,
        p_out9 => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9,
        p_out9_ap_vld => grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln315_fu_406_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_84 <= ap_const_lv17_0;
            elsif (((icmp_ln315_fu_406_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_84 <= y_8_fu_411_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln315_1_reg_769 <= add_ln315_1_fu_382_p2;
                loopHeight_reg_753 <= loopHeight_fu_338_p2;
                trunc_ln293_1_reg_758 <= bayerPhase_read(15 downto 1);
                    xor229_1_cast_reg_774(0) <= xor229_1_cast_fu_394_p1(0);
                    zext_ln274_reg_748(15 downto 0) <= zext_ln274_fu_334_p1(15 downto 0);
                    zext_ln294_reg_764(0) <= zext_ln294_fu_362_p1(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_10_fu_160 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_30_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                bayerWindow_10_load_reg_892 <= bayerWindow_10_fu_160;
                bayerWindow_12_load_reg_897 <= bayerWindow_12_fu_164;
                bayerWindow_13_load_reg_902 <= bayerWindow_13_fu_168;
                bayerWindow_14_load_reg_907 <= bayerWindow_14_fu_172;
                bayerWindow_16_load_reg_912 <= bayerWindow_16_fu_176;
                bayerWindow_17_load_reg_917 <= bayerWindow_17_fu_180;
                bayerWindow_18_load_reg_922 <= bayerWindow_18_fu_184;
                bayerWindow_1_load_reg_857 <= bayerWindow_1_fu_132;
                bayerWindow_2_load_reg_862 <= bayerWindow_2_fu_136;
                bayerWindow_4_load_reg_867 <= bayerWindow_4_fu_140;
                bayerWindow_5_load_reg_872 <= bayerWindow_5_fu_144;
                bayerWindow_6_load_reg_877 <= bayerWindow_6_fu_148;
                bayerWindow_8_load_reg_882 <= bayerWindow_8_fu_152;
                bayerWindow_9_load_reg_887 <= bayerWindow_9_fu_156;
                bayerWindow_load_reg_852 <= bayerWindow_fu_128;
                cmp230_1_reg_962 <= cmp230_1_fu_551_p2;
                cmp230_reg_957 <= cmp230_fu_546_p2;
                cmp689_reg_952 <= cmp689_fu_541_p2;
                p_lcssa54535492_load_reg_807 <= p_lcssa54535492_fu_92;
                p_lcssa54575494_load_reg_812 <= p_lcssa54575494_fu_96;
                p_lcssa54595496_load_reg_817 <= p_lcssa54595496_fu_100;
                p_lcssa54635498_load_reg_822 <= p_lcssa54635498_fu_104;
                p_lcssa54655500_load_reg_827 <= p_lcssa54655500_fu_108;
                p_lcssa54695502_load_reg_832 <= p_lcssa54695502_fu_112;
                p_lcssa54715504_load_reg_837 <= p_lcssa54715504_fu_116;
                p_lcssa54755506_load_reg_842 <= p_lcssa54755506_fu_120;
                p_lcssa54775508_load_reg_847 <= p_lcssa54775508_fu_124;
                p_lcssa5490_load_reg_802 <= p_lcssa5490_fu_88;
                pixBuf_195_load_reg_932 <= pixBuf_195_fu_192;
                pixBuf_196_load_reg_937 <= pixBuf_196_fu_196;
                pixBuf_197_load_reg_942 <= pixBuf_197_fu_200;
                pixBuf_198_load_reg_947 <= pixBuf_198_fu_204;
                pixBuf_load_reg_927 <= pixBuf_fu_188;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_12_fu_164 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_32_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_13_fu_168 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_33_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_14_fu_172 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_34_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_16_fu_176 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_36_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_17_fu_180 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_37_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_18_fu_184 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_38_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_1_fu_132 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_21_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_2_fu_136 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_22_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_4_fu_140 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_24_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_5_fu_144 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_25_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_6_fu_148 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_26_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_8_fu_152 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_28_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_9_fu_156 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_29_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                bayerWindow_fu_128 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_20_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp170_reg_797 <= cmp170_fu_432_p2;
                cmp84_reg_792 <= cmp84_fu_427_p2;
                empty_reg_787 <= empty_fu_423_p1;
                out_y_reg_782 <= out_y_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54535492_fu_92 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54575494_fu_96 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54595496_fu_100 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54635498_fu_104 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54655500_fu_108 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54695502_fu_112 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54715504_fu_116 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54755506_fu_120 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa54775508_fu_124 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_lcssa5490_fu_88 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_p_out9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_195_fu_192 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_88_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_196_fu_196 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_87_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_197_fu_200 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_86_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_198_fu_204 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_85_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_fu_188 <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_bayerWindow_89_out;
            end if;
        end if;
    end process;
    zext_ln274_reg_748(16) <= '0';
    zext_ln294_reg_764(14 downto 1) <= "00000000000000";
    xor229_1_cast_reg_774(14 downto 1) <= "00000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done, ap_CS_fsm_state5, icmp_ln315_fu_406_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln315_fu_406_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln315_1_fu_382_p2 <= std_logic_vector(unsigned(trunc_ln_fu_372_p4) + unsigned(ap_const_lv15_1));
    add_ln315_fu_366_p2 <= std_logic_vector(unsigned(zext_ln283_fu_344_p1) + unsigned(ap_const_lv17_3));
    and226_cast_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_787),15));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done)
    begin
        if ((grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, bayerPhase_c9_full_n)
    begin
                ap_block_state1 <= ((bayerPhase_c9_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln315_fu_406_p2)
    begin
        if (((icmp_ln315_fu_406_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_c9_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, bayerPhase_c9_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_blk_n <= bayerPhase_c9_full_n;
        else 
            bayerPhase_c9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_c9_din <= bayerPhase_read;

    bayerPhase_c9_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bayerPhase_c9_write <= ap_const_logic_1;
        else 
            bayerPhase_c9_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp170_fu_432_p2 <= "0" when (y_fu_84 = ap_const_lv17_0) else "1";
    cmp230_1_fu_551_p2 <= "0" when (xor_fu_536_p2 = xor229_1_cast_reg_774) else "1";
    cmp230_fu_546_p2 <= "0" when (xor_fu_536_p2 = zext_ln294_reg_764) else "1";
    cmp689_fu_541_p2 <= "1" when (and226_cast_fu_533_p1 = trunc_ln293_1_reg_758) else "0";
    cmp84_fu_427_p2 <= "1" when (unsigned(y_fu_84) < unsigned(zext_ln274_reg_748)) else "0";
    empty_fu_423_p1 <= out_y_fu_417_p2(1 - 1 downto 0);
    grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_ap_start_reg;
    icmp_ln315_fu_406_p2 <= "1" when (y_fu_84 = loopHeight_reg_753) else "0";

    imgBayer_read_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgBayer_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imgBayer_read <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgBayer_read;
        else 
            imgBayer_read <= ap_const_logic_0;
        end if; 
    end process;

    imgG_din <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_din;

    imgG_write_assign_proc : process(grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imgG_write <= grp_DebayerG_Pipeline_VITIS_LOOP_318_4_fu_250_imgG_write;
        else 
            imgG_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln315_fu_406_p2)
    begin
        if (((icmp_ln315_fu_406_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_338_p2 <= std_logic_vector(unsigned(zext_ln274_fu_334_p1) + unsigned(ap_const_lv17_2));
    out_y_fu_417_p2 <= std_logic_vector(unsigned(y_fu_84) + unsigned(ap_const_lv17_1FFFE));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln_fu_372_p4 <= add_ln315_fu_366_p2(16 downto 2);
    x_phase_fu_348_p1 <= bayerPhase_read(1 - 1 downto 0);
    xor229_1_cast_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor229_1_fu_388_p2),15));
    xor229_1_fu_388_p2 <= (x_phase_fu_348_p1 xor ap_const_lv1_1);
    xor_fu_536_p2 <= (trunc_ln293_1_reg_758 xor and226_cast_fu_533_p1);
    y_8_fu_411_p2 <= std_logic_vector(unsigned(y_fu_84) + unsigned(ap_const_lv17_1));
    zext_ln274_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height),17));
    zext_ln283_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width),17));
    zext_ln294_fu_362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_phase_fu_348_p1),15));
end behav;
