// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_0_DebayerRatBorBatR (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgG_dout,
        imgG_num_data_valid,
        imgG_fifo_cap,
        imgG_empty_n,
        imgG_read,
        imgRB_din,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_full_n,
        imgRB_write,
        height,
        width,
        bayerPhase_c9_dout,
        bayerPhase_c9_num_data_valid,
        bayerPhase_c9_fifo_cap,
        bayerPhase_c9_empty_n,
        bayerPhase_c9_read,
        bayerPhase_c_din,
        bayerPhase_c_num_data_valid,
        bayerPhase_c_fifo_cap,
        bayerPhase_c_full_n,
        bayerPhase_c_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [119:0] imgG_dout;
input  [2:0] imgG_num_data_valid;
input  [2:0] imgG_fifo_cap;
input   imgG_empty_n;
output   imgG_read;
output  [119:0] imgRB_din;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
input   imgRB_full_n;
output   imgRB_write;
input  [9:0] height;
input  [9:0] width;
input  [15:0] bayerPhase_c9_dout;
input  [2:0] bayerPhase_c9_num_data_valid;
input  [2:0] bayerPhase_c9_fifo_cap;
input   bayerPhase_c9_empty_n;
output   bayerPhase_c9_read;
output  [15:0] bayerPhase_c_din;
input  [2:0] bayerPhase_c_num_data_valid;
input  [2:0] bayerPhase_c_fifo_cap;
input   bayerPhase_c_full_n;
output   bayerPhase_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgG_read;
reg imgRB_write;
reg bayerPhase_c9_read;
reg bayerPhase_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
wire    ap_CS_fsm_state2;
reg    bayerPhase_c_blk_n;
reg    ap_block_state1;
reg    ap_block_state2;
wire   [9:0] loopHeight_fu_388_p2;
reg   [9:0] loopHeight_reg_903;
reg   [14:0] trunc_ln622_1_i_reg_908;
wire   [14:0] zext_ln623_fu_408_p1;
reg   [14:0] zext_ln623_reg_914;
wire   [7:0] add_ln630_1_fu_427_p2;
reg   [7:0] add_ln630_1_reg_919;
wire   [14:0] xor313_1_cast_i_fu_439_p1;
reg   [14:0] xor313_1_cast_i_reg_924;
reg   [9:0] p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932;
wire    ap_CS_fsm_state3;
reg   [9:0] p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937;
reg   [9:0] p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942;
reg   [9:0] p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947;
reg   [9:0] p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952;
reg   [9:0] p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957;
reg   [9:0] pixWindow_load_reg_962;
reg   [9:0] pixWindow_141_load_reg_967;
reg   [9:0] pixWindow_142_load_reg_972;
reg   [9:0] pixWindow_143_load_reg_977;
reg   [9:0] pixWindow_144_load_reg_982;
reg   [9:0] pixWindow_145_load_reg_987;
reg   [9:0] pixWindow_146_load_reg_992;
reg   [9:0] pixWindow_147_load_reg_997;
reg   [9:0] pixWindow_148_load_reg_1002;
reg   [9:0] pixWindow_149_load_reg_1007;
reg   [9:0] pixWindow_150_load_reg_1012;
reg   [9:0] pixWindow_151_load_reg_1017;
reg   [9:0] pixWindow_152_load_reg_1022;
reg   [9:0] pixWindow_153_load_reg_1027;
reg   [9:0] pixWindow_154_load_reg_1032;
reg   [9:0] pixWindow_155_load_reg_1037;
reg   [9:0] pixWindow_156_load_reg_1042;
reg   [9:0] pixWindow_157_load_reg_1047;
reg   [9:0] pixWindow_158_load_reg_1052;
reg   [9:0] pixWindow_159_load_reg_1057;
reg   [9:0] pixWindow_160_load_reg_1062;
reg   [9:0] pixWindow_161_load_reg_1067;
reg   [9:0] pixWindow_162_load_reg_1072;
reg   [9:0] pixWindow_163_load_reg_1077;
reg   [9:0] pixWindow_164_load_reg_1082;
reg   [9:0] pixWindow_165_load_reg_1087;
reg   [9:0] pixWindow_166_load_reg_1092;
reg   [9:0] pixBuf_load_reg_1097;
reg   [9:0] pixBuf_78_load_reg_1102;
reg   [9:0] pixBuf_79_load_reg_1107;
reg   [9:0] pixBuf_80_load_reg_1112;
reg   [9:0] pixBuf_81_load_reg_1117;
reg   [9:0] pixBuf_82_load_reg_1122;
reg   [9:0] pixBuf_83_load_reg_1127;
reg   [9:0] pixBuf_84_load_reg_1132;
reg   [9:0] pixBuf_85_load_reg_1137;
wire   [0:0] red_i_fu_602_p2;
reg   [0:0] red_i_reg_1142;
wire   [0:0] cmp558_i_fu_607_p2;
reg   [0:0] cmp558_i_reg_1147;
wire   [0:0] cmp59_i_fu_613_p2;
reg   [0:0] cmp59_i_reg_1152;
wire   [0:0] cmp314_i_fu_618_p2;
reg   [0:0] cmp314_i_reg_1157;
wire   [0:0] cmp314_1_i_fu_623_p2;
reg   [0:0] cmp314_1_i_reg_1162;
wire   [119:0] lineBuffer_q1;
wire   [119:0] lineBuffer_1_q1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_idle;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read;
wire   [119:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0;
wire   [119:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0;
wire   [119:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0;
wire   [7:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld;
reg    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [9:0] pixBuf_85_fu_244;
reg   [9:0] pixBuf_84_fu_240;
reg   [9:0] pixBuf_83_fu_236;
reg   [9:0] pixBuf_82_fu_232;
reg   [9:0] pixBuf_81_fu_228;
reg   [9:0] pixBuf_80_fu_224;
reg   [9:0] pixBuf_79_fu_220;
reg   [9:0] pixBuf_78_fu_216;
reg   [9:0] pixBuf_fu_212;
reg   [9:0] pixWindow_166_fu_208;
reg   [9:0] pixWindow_165_fu_204;
reg   [9:0] pixWindow_164_fu_200;
reg   [9:0] pixWindow_163_fu_196;
reg   [9:0] pixWindow_162_fu_192;
reg   [9:0] pixWindow_161_fu_188;
reg   [9:0] pixWindow_160_fu_184;
reg   [9:0] pixWindow_159_fu_180;
reg   [9:0] pixWindow_158_fu_176;
reg   [9:0] pixWindow_157_fu_172;
reg   [9:0] pixWindow_156_fu_168;
reg   [9:0] pixWindow_155_fu_164;
reg   [9:0] pixWindow_154_fu_160;
reg   [9:0] pixWindow_153_fu_156;
reg   [9:0] pixWindow_152_fu_152;
reg   [9:0] pixWindow_151_fu_148;
reg   [9:0] pixWindow_150_fu_144;
reg   [9:0] pixWindow_149_fu_140;
reg   [9:0] pixWindow_148_fu_136;
reg   [9:0] pixWindow_147_fu_132;
reg   [9:0] pixWindow_146_fu_128;
reg   [9:0] pixWindow_145_fu_124;
reg   [9:0] pixWindow_144_fu_120;
reg   [9:0] pixWindow_143_fu_116;
reg   [9:0] pixWindow_142_fu_112;
reg   [9:0] pixWindow_141_fu_108;
reg   [9:0] pixWindow_fu_104;
reg   [9:0] p_0_2_0_0_0925_21699_lcssa1771_i_fu_100;
reg   [9:0] p_0_1_0_0_0924_21696_lcssa1769_i_fu_96;
reg   [9:0] p_0_0_0_0_0923_21693_lcssa1767_i_fu_92;
reg   [9:0] p_0_2_0_0_0931_21633_lcssa1759_i_fu_88;
reg   [9:0] p_0_1_0_0_0930_21630_lcssa1757_i_fu_84;
reg   [9:0] p_0_0_0_0_0929_21627_lcssa1755_i_fu_80;
reg   [9:0] y_fu_76;
wire   [9:0] y_4_fu_451_p2;
wire   [0:0] icmp_ln630_fu_446_p2;
wire   [0:0] x_phase_fu_394_p1;
wire   [9:0] add_ln630_fu_412_p2;
wire   [7:0] trunc_ln_i_fu_417_p4;
wire   [0:0] xor313_1_i_fu_433_p2;
wire   [0:0] trunc_ln630_fu_583_p1;
wire   [0:0] and310_i_fu_587_p2;
wire   [14:0] and310_cast_i_fu_593_p1;
wire   [14:0] xor_i_fu_597_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg = 1'b0;
#0 y_fu_76 = 10'd0;
end

system_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 120 ),
    .AddressRange( 181 ),
    .AddressWidth( 8 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1),
    .q1(lineBuffer_q1)
);

system_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 120 ),
    .AddressRange( 181 ),
    .AddressWidth( 8 ))
lineBuffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1),
    .q1(lineBuffer_1_q1)
);

system_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start),
    .ap_done(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done),
    .ap_idle(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_idle),
    .ap_ready(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready),
    .imgG_dout(imgG_dout),
    .imgG_num_data_valid(imgG_num_data_valid),
    .imgG_fifo_cap(imgG_fifo_cap),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read),
    .imgRB_din(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din),
    .imgRB_num_data_valid(3'd0),
    .imgRB_fifo_cap(3'd0),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write),
    .pixWindow_146_i(pixBuf_85_load_reg_1137),
    .pixWindow_145_i(pixBuf_84_load_reg_1132),
    .pixWindow_144_i(pixBuf_83_load_reg_1127),
    .pixWindow_149_i(pixBuf_82_load_reg_1122),
    .pixWindow_148_i(pixBuf_81_load_reg_1117),
    .pixWindow_147_i(pixBuf_80_load_reg_1112),
    .pixWindow_152_i(pixBuf_79_load_reg_1107),
    .pixWindow_151_i(pixBuf_78_load_reg_1102),
    .pixWindow_150_i(pixBuf_load_reg_1097),
    .pixWindow_32_i(pixWindow_166_load_reg_1092),
    .pixWindow_31_i(pixWindow_165_load_reg_1087),
    .pixWindow_30_i(pixWindow_164_load_reg_1082),
    .pixWindow_29_i(pixWindow_163_load_reg_1077),
    .pixWindow_28_i(pixWindow_162_load_reg_1072),
    .pixWindow_27_i(pixWindow_161_load_reg_1067),
    .pixWindow_26_i(pixWindow_160_load_reg_1062),
    .pixWindow_25_i(pixWindow_159_load_reg_1057),
    .pixWindow_24_i(pixWindow_158_load_reg_1052),
    .pixWindow_20_i(pixWindow_157_load_reg_1047),
    .pixWindow_19_i(pixWindow_156_load_reg_1042),
    .pixWindow_18_i(pixWindow_155_load_reg_1037),
    .pixWindow_17_i(pixWindow_154_load_reg_1032),
    .pixWindow_16_i(pixWindow_153_load_reg_1027),
    .pixWindow_15_i(pixWindow_152_load_reg_1022),
    .pixWindow_14_i(pixWindow_151_load_reg_1017),
    .pixWindow_13_i(pixWindow_150_load_reg_1012),
    .pixWindow_12_i(pixWindow_149_load_reg_1007),
    .pixWindow_8_i(pixWindow_148_load_reg_1002),
    .pixWindow_7_i(pixWindow_147_load_reg_997),
    .pixWindow_6_i(pixWindow_146_load_reg_992),
    .pixWindow_5_i(pixWindow_145_load_reg_987),
    .pixWindow_4_i(pixWindow_144_load_reg_982),
    .pixWindow_3_i(pixWindow_143_load_reg_977),
    .pixWindow_2_i(pixWindow_142_load_reg_972),
    .pixWindow_1_i(pixWindow_141_load_reg_967),
    .pixWindow_i(pixWindow_load_reg_962),
    .p_0_2_0_0_0925_21699_lcssa1771_i(p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957),
    .p_0_1_0_0_0924_21696_lcssa1769_i(p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952),
    .p_0_0_0_0_0923_21693_lcssa1767_i(p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947),
    .p_0_2_0_0_0931_21633_lcssa1759_i(p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942),
    .p_0_1_0_0_0930_21630_lcssa1757_i(p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937),
    .p_0_0_0_0_0929_21627_lcssa1755_i(p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932),
    .add_ln630_1_i(add_ln630_1_reg_919),
    .cmp558_i(cmp558_i_reg_1147),
    .cmp314_1_i(cmp314_1_i_reg_1162),
    .cmp314_i(cmp314_i_reg_1157),
    .lineBuffer_1_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0),
    .lineBuffer_1_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0),
    .lineBuffer_1_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0),
    .lineBuffer_1_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0),
    .lineBuffer_1_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1),
    .lineBuffer_1_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1),
    .lineBuffer_1_i_q1(lineBuffer_1_q1),
    .lineBuffer_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0),
    .lineBuffer_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0),
    .lineBuffer_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0),
    .lineBuffer_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0),
    .lineBuffer_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1),
    .lineBuffer_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1),
    .lineBuffer_i_q1(lineBuffer_q1),
    .empty(width),
    .cmp59_i(cmp59_i_reg_1152),
    .red_i(red_i_reg_1142),
    .pixWindow_155_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out),
    .pixWindow_155_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld),
    .pixWindow_154_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out),
    .pixWindow_154_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld),
    .pixWindow_153_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out),
    .pixWindow_153_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld),
    .pixWindow_158_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out),
    .pixWindow_158_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld),
    .pixWindow_157_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out),
    .pixWindow_157_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld),
    .pixWindow_156_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out),
    .pixWindow_156_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld),
    .pixWindow_161_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out),
    .pixWindow_161_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld),
    .pixWindow_160_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out),
    .pixWindow_160_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld),
    .pixWindow_159_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out),
    .pixWindow_159_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld),
    .pixWindow_68_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out),
    .pixWindow_68_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld),
    .pixWindow_67_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out),
    .pixWindow_67_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld),
    .pixWindow_66_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out),
    .pixWindow_66_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld),
    .pixWindow_65_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out),
    .pixWindow_65_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld),
    .pixWindow_64_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out),
    .pixWindow_64_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld),
    .pixWindow_63_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out),
    .pixWindow_63_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld),
    .pixWindow_62_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out),
    .pixWindow_62_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld),
    .pixWindow_61_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out),
    .pixWindow_61_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld),
    .pixWindow_60_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out),
    .pixWindow_60_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld),
    .pixWindow_56_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out),
    .pixWindow_56_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld),
    .pixWindow_55_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out),
    .pixWindow_55_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld),
    .pixWindow_54_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out),
    .pixWindow_54_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld),
    .pixWindow_53_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out),
    .pixWindow_53_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld),
    .pixWindow_52_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out),
    .pixWindow_52_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld),
    .pixWindow_51_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out),
    .pixWindow_51_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld),
    .pixWindow_50_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out),
    .pixWindow_50_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld),
    .pixWindow_49_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out),
    .pixWindow_49_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld),
    .pixWindow_48_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out),
    .pixWindow_48_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld),
    .pixWindow_44_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out),
    .pixWindow_44_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld),
    .pixWindow_43_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out),
    .pixWindow_43_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld),
    .pixWindow_42_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out),
    .pixWindow_42_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld),
    .pixWindow_41_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out),
    .pixWindow_41_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld),
    .pixWindow_40_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out),
    .pixWindow_40_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld),
    .pixWindow_39_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out),
    .pixWindow_39_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld),
    .pixWindow_38_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out),
    .pixWindow_38_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld),
    .pixWindow_37_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out),
    .pixWindow_37_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld),
    .pixWindow_36_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out),
    .pixWindow_36_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld),
    .p_0_2_0_0_0925_21701_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out),
    .p_0_2_0_0_0925_21701_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld),
    .p_0_1_0_0_0924_21698_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out),
    .p_0_1_0_0_0924_21698_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld),
    .p_0_0_0_0_0923_21695_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out),
    .p_0_0_0_0_0923_21695_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld),
    .p_0_2_0_0_0931_21635_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out),
    .p_0_2_0_0_0931_21635_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld),
    .p_0_1_0_0_0930_21632_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out),
    .p_0_1_0_0_0930_21632_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld),
    .p_0_0_0_0_0929_21629_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out),
    .p_0_0_0_0_0929_21629_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln630_fu_446_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready == 1'b1)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_76 <= 10'd0;
    end else if (((icmp_ln630_fu_446_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_76 <= y_4_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln630_1_reg_919 <= add_ln630_1_fu_427_p2;
        loopHeight_reg_903 <= loopHeight_fu_388_p2;
        trunc_ln622_1_i_reg_908 <= {{bayerPhase_c9_dout[15:1]}};
        xor313_1_cast_i_reg_924[0] <= xor313_1_cast_i_fu_439_p1[0];
        zext_ln623_reg_914[0] <= zext_ln623_fu_408_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp314_1_i_reg_1162 <= cmp314_1_i_fu_623_p2;
        cmp314_i_reg_1157 <= cmp314_i_fu_618_p2;
        cmp558_i_reg_1147 <= cmp558_i_fu_607_p2;
        cmp59_i_reg_1152 <= cmp59_i_fu_613_p2;
        p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947 <= p_0_0_0_0_0923_21693_lcssa1767_i_fu_92;
        p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932 <= p_0_0_0_0_0929_21627_lcssa1755_i_fu_80;
        p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952 <= p_0_1_0_0_0924_21696_lcssa1769_i_fu_96;
        p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937 <= p_0_1_0_0_0930_21630_lcssa1757_i_fu_84;
        p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957 <= p_0_2_0_0_0925_21699_lcssa1771_i_fu_100;
        p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942 <= p_0_2_0_0_0931_21633_lcssa1759_i_fu_88;
        pixBuf_78_load_reg_1102 <= pixBuf_78_fu_216;
        pixBuf_79_load_reg_1107 <= pixBuf_79_fu_220;
        pixBuf_80_load_reg_1112 <= pixBuf_80_fu_224;
        pixBuf_81_load_reg_1117 <= pixBuf_81_fu_228;
        pixBuf_82_load_reg_1122 <= pixBuf_82_fu_232;
        pixBuf_83_load_reg_1127 <= pixBuf_83_fu_236;
        pixBuf_84_load_reg_1132 <= pixBuf_84_fu_240;
        pixBuf_85_load_reg_1137 <= pixBuf_85_fu_244;
        pixBuf_load_reg_1097 <= pixBuf_fu_212;
        pixWindow_141_load_reg_967 <= pixWindow_141_fu_108;
        pixWindow_142_load_reg_972 <= pixWindow_142_fu_112;
        pixWindow_143_load_reg_977 <= pixWindow_143_fu_116;
        pixWindow_144_load_reg_982 <= pixWindow_144_fu_120;
        pixWindow_145_load_reg_987 <= pixWindow_145_fu_124;
        pixWindow_146_load_reg_992 <= pixWindow_146_fu_128;
        pixWindow_147_load_reg_997 <= pixWindow_147_fu_132;
        pixWindow_148_load_reg_1002 <= pixWindow_148_fu_136;
        pixWindow_149_load_reg_1007 <= pixWindow_149_fu_140;
        pixWindow_150_load_reg_1012 <= pixWindow_150_fu_144;
        pixWindow_151_load_reg_1017 <= pixWindow_151_fu_148;
        pixWindow_152_load_reg_1022 <= pixWindow_152_fu_152;
        pixWindow_153_load_reg_1027 <= pixWindow_153_fu_156;
        pixWindow_154_load_reg_1032 <= pixWindow_154_fu_160;
        pixWindow_155_load_reg_1037 <= pixWindow_155_fu_164;
        pixWindow_156_load_reg_1042 <= pixWindow_156_fu_168;
        pixWindow_157_load_reg_1047 <= pixWindow_157_fu_172;
        pixWindow_158_load_reg_1052 <= pixWindow_158_fu_176;
        pixWindow_159_load_reg_1057 <= pixWindow_159_fu_180;
        pixWindow_160_load_reg_1062 <= pixWindow_160_fu_184;
        pixWindow_161_load_reg_1067 <= pixWindow_161_fu_188;
        pixWindow_162_load_reg_1072 <= pixWindow_162_fu_192;
        pixWindow_163_load_reg_1077 <= pixWindow_163_fu_196;
        pixWindow_164_load_reg_1082 <= pixWindow_164_fu_200;
        pixWindow_165_load_reg_1087 <= pixWindow_165_fu_204;
        pixWindow_166_load_reg_1092 <= pixWindow_166_fu_208;
        pixWindow_load_reg_962 <= pixWindow_fu_104;
        red_i_reg_1142 <= red_i_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0_0_0923_21693_lcssa1767_i_fu_92 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0_0_0929_21627_lcssa1755_i_fu_80 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_1_0_0_0924_21696_lcssa1769_i_fu_96 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_1_0_0_0930_21630_lcssa1757_i_fu_84 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_2_0_0_0925_21699_lcssa1771_i_fu_100 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_2_0_0_0931_21633_lcssa1759_i_fu_88 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_78_fu_216 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_79_fu_220 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_80_fu_224 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_81_fu_228 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_82_fu_232 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_83_fu_236 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_84_fu_240 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_85_fu_244 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_fu_212 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_141_fu_108 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_142_fu_112 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_143_fu_116 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_144_fu_120 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_145_fu_124 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_146_fu_128 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_147_fu_132 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_148_fu_136 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_149_fu_140 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_150_fu_144 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_151_fu_148 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_152_fu_152 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_153_fu_156 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_154_fu_160 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_155_fu_164 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_156_fu_168 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_157_fu_172 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_158_fu_176 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_159_fu_180 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_160_fu_184 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_161_fu_188 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_162_fu_192 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_163_fu_196 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_164_fu_200 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_165_fu_204 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_166_fu_208 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_fu_104 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln630_fu_446_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_empty_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        bayerPhase_c9_read = 1'b1;
    end else begin
        bayerPhase_c9_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bayerPhase_c_blk_n = bayerPhase_c_full_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        bayerPhase_c_write = 1'b1;
    end else begin
        bayerPhase_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imgG_read = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read;
    end else begin
        imgG_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imgRB_write = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write;
    end else begin
        imgRB_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln630_fu_446_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln630_fu_446_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln630_1_fu_427_p2 = (trunc_ln_i_fu_417_p4 + 8'd1);

assign add_ln630_fu_412_p2 = (width + 10'd3);

assign and310_cast_i_fu_593_p1 = and310_i_fu_587_p2;

assign and310_i_fu_587_p2 = (trunc_ln630_fu_583_p1 ^ 1'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c_din = bayerPhase_c9_dout;

assign cmp314_1_i_fu_623_p2 = ((xor_i_fu_597_p2 == xor313_1_cast_i_reg_924) ? 1'b1 : 1'b0);

assign cmp314_i_fu_618_p2 = ((xor_i_fu_597_p2 == zext_ln623_reg_914) ? 1'b1 : 1'b0);

assign cmp558_i_fu_607_p2 = ((y_fu_76 != 10'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_613_p2 = ((y_fu_76 < height) ? 1'b1 : 1'b0);

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg;

assign icmp_ln630_fu_446_p2 = ((y_fu_76 == loopHeight_reg_903) ? 1'b1 : 1'b0);

assign imgRB_din = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din;

assign loopHeight_fu_388_p2 = (height + 10'd1);

assign red_i_fu_602_p2 = ((and310_cast_i_fu_593_p1 == trunc_ln622_1_i_reg_908) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign trunc_ln630_fu_583_p1 = y_fu_76[0:0];

assign trunc_ln_i_fu_417_p4 = {{add_ln630_fu_412_p2[9:2]}};

assign x_phase_fu_394_p1 = bayerPhase_c9_dout[0:0];

assign xor313_1_cast_i_fu_439_p1 = xor313_1_i_fu_433_p2;

assign xor313_1_i_fu_433_p2 = (x_phase_fu_394_p1 ^ 1'd1);

assign xor_i_fu_597_p2 = (trunc_ln622_1_i_reg_908 ^ and310_cast_i_fu_593_p1);

assign y_4_fu_451_p2 = (y_fu_76 + 10'd1);

assign zext_ln623_fu_408_p1 = x_phase_fu_394_p1;

always @ (posedge ap_clk) begin
    zext_ln623_reg_914[14:1] <= 14'b00000000000000;
    xor313_1_cast_i_reg_924[14:1] <= 14'b00000000000000;
end

endmodule //system_v_demosaic_0_0_DebayerRatBorBatR
