// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_0_DebayerRandBatG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        height,
        width,
        bayerPhase_c_dout,
        bayerPhase_c_num_data_valid,
        bayerPhase_c_fifo_cap,
        bayerPhase_c_empty_n,
        bayerPhase_c_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [119:0] imgRB_dout;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [119:0] imgRgb_din;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [9:0] height;
input  [9:0] width;
input  [15:0] bayerPhase_c_dout;
input  [2:0] bayerPhase_c_num_data_valid;
input  [2:0] bayerPhase_c_fifo_cap;
input   bayerPhase_c_empty_n;
output   bayerPhase_c_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgRB_read;
reg imgRgb_write;
reg bayerPhase_c_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bayerPhase_c_blk_n;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
wire   [9:0] loopHeight_fu_357_p2;
reg   [9:0] loopHeight_reg_840;
reg   [14:0] trunc_ln870_1_i_reg_845;
wire   [14:0] zext_ln871_fu_377_p1;
reg   [14:0] zext_ln871_reg_850;
wire   [7:0] add_ln878_1_fu_396_p2;
reg   [7:0] add_ln878_1_reg_855;
wire   [14:0] xor309_1_cast_i_fu_408_p1;
reg   [14:0] xor309_1_cast_i_reg_860;
reg   [9:0] p_0_0_0_0_01166_31936_lcssa2033_i_load_reg_868;
wire    ap_CS_fsm_state3;
reg   [9:0] p_0_1_0_0_01167_31939_lcssa2035_i_load_reg_873;
reg   [9:0] p_0_2_0_0_01168_31942_lcssa2037_i_load_reg_878;
reg   [9:0] pixWindow_load_reg_883;
reg   [9:0] pixWindow_304_load_reg_888;
reg   [9:0] pixWindow_305_load_reg_893;
reg   [9:0] pixWindow_306_load_reg_898;
reg   [9:0] pixWindow_307_load_reg_903;
reg   [9:0] pixWindow_308_load_reg_908;
reg   [9:0] pixWindow_309_load_reg_913;
reg   [9:0] pixWindow_310_load_reg_918;
reg   [9:0] pixWindow_311_load_reg_923;
reg   [9:0] pixWindow_312_load_reg_928;
reg   [9:0] pixWindow_313_load_reg_933;
reg   [9:0] pixWindow_314_load_reg_938;
reg   [9:0] pixWindow_315_load_reg_943;
reg   [9:0] pixWindow_316_load_reg_948;
reg   [9:0] pixWindow_317_load_reg_953;
reg   [9:0] pixWindow_318_load_reg_958;
reg   [9:0] pixWindow_319_load_reg_963;
reg   [9:0] pixWindow_320_load_reg_968;
reg   [9:0] pixWindow_321_load_reg_973;
reg   [9:0] pixWindow_322_load_reg_978;
reg   [9:0] pixWindow_323_load_reg_983;
reg   [9:0] pixWindow_324_load_reg_988;
reg   [9:0] pixWindow_325_load_reg_993;
reg   [9:0] pixWindow_326_load_reg_998;
reg   [9:0] pixWindow_327_load_reg_1003;
reg   [9:0] pixWindow_328_load_reg_1008;
reg   [9:0] pixWindow_329_load_reg_1013;
reg   [9:0] pixBuf_load_reg_1018;
reg   [9:0] pixBuf_163_load_reg_1023;
reg   [9:0] pixBuf_164_load_reg_1028;
reg   [9:0] pixBuf_165_load_reg_1033;
reg   [9:0] pixBuf_166_load_reg_1038;
reg   [9:0] pixBuf_167_load_reg_1043;
reg   [9:0] pixBuf_168_load_reg_1048;
reg   [9:0] pixBuf_169_load_reg_1053;
reg   [9:0] pixBuf_170_load_reg_1058;
wire   [0:0] cmp478_i_fu_562_p2;
reg   [0:0] cmp478_i_reg_1063;
wire   [0:0] cmp59_i_fu_568_p2;
reg   [0:0] cmp59_i_reg_1068;
wire   [0:0] cmp310_i_fu_573_p2;
reg   [0:0] cmp310_i_reg_1073;
wire   [0:0] cmp310_1_i_fu_578_p2;
reg   [0:0] cmp310_1_i_reg_1078;
wire   [119:0] lineBuffer_q1;
wire   [119:0] lineBuffer_2_q1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_done;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_idle;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_ready;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRB_read;
wire   [119:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_din;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_write;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_we0;
wire   [119:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_d0;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce1;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_we0;
wire   [119:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_d0;
wire   [7:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce1;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out_ap_vld;
reg    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [9:0] pixBuf_170_fu_228;
reg   [9:0] pixBuf_169_fu_224;
reg   [9:0] pixBuf_168_fu_220;
reg   [9:0] pixBuf_167_fu_216;
reg   [9:0] pixBuf_166_fu_212;
reg   [9:0] pixBuf_165_fu_208;
reg   [9:0] pixBuf_164_fu_204;
reg   [9:0] pixBuf_163_fu_200;
reg   [9:0] pixBuf_fu_196;
reg   [9:0] pixWindow_329_fu_192;
reg   [9:0] pixWindow_328_fu_188;
reg   [9:0] pixWindow_327_fu_184;
reg   [9:0] pixWindow_326_fu_180;
reg   [9:0] pixWindow_325_fu_176;
reg   [9:0] pixWindow_324_fu_172;
reg   [9:0] pixWindow_323_fu_168;
reg   [9:0] pixWindow_322_fu_164;
reg   [9:0] pixWindow_321_fu_160;
reg   [9:0] pixWindow_320_fu_156;
reg   [9:0] pixWindow_319_fu_152;
reg   [9:0] pixWindow_318_fu_148;
reg   [9:0] pixWindow_317_fu_144;
reg   [9:0] pixWindow_316_fu_140;
reg   [9:0] pixWindow_315_fu_136;
reg   [9:0] pixWindow_314_fu_132;
reg   [9:0] pixWindow_313_fu_128;
reg   [9:0] pixWindow_312_fu_124;
reg   [9:0] pixWindow_311_fu_120;
reg   [9:0] pixWindow_310_fu_116;
reg   [9:0] pixWindow_309_fu_112;
reg   [9:0] pixWindow_308_fu_108;
reg   [9:0] pixWindow_307_fu_104;
reg   [9:0] pixWindow_306_fu_100;
reg   [9:0] pixWindow_305_fu_96;
reg   [9:0] pixWindow_304_fu_92;
reg   [9:0] pixWindow_fu_88;
reg   [9:0] p_0_2_0_0_01168_31942_lcssa2037_i_fu_84;
reg   [9:0] p_0_1_0_0_01167_31939_lcssa2035_i_fu_80;
reg   [9:0] p_0_0_0_0_01166_31936_lcssa2033_i_fu_76;
reg   [9:0] y_fu_72;
wire   [9:0] y_6_fu_420_p2;
wire   [0:0] icmp_ln878_fu_415_p2;
wire   [0:0] x_phase_fu_363_p1;
wire   [9:0] add_ln878_fu_381_p2;
wire   [7:0] trunc_ln_i_fu_386_p4;
wire   [0:0] xor309_1_i_fu_402_p2;
wire   [0:0] trunc_ln878_fu_543_p1;
wire   [0:0] tmp_i_fu_547_p2;
wire   [14:0] tmp_cast_i_fu_553_p1;
wire   [14:0] xor_i_fu_557_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg = 1'b0;
#0 y_fu_72 = 10'd0;
end

system_v_demosaic_0_0_DebayerRandBatG_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 120 ),
    .AddressRange( 181 ),
    .AddressWidth( 8 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce1),
    .q1(lineBuffer_q1)
);

system_v_demosaic_0_0_DebayerRandBatG_lineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 120 ),
    .AddressRange( 181 ),
    .AddressWidth( 8 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce1),
    .q1(lineBuffer_2_q1)
);

system_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start),
    .ap_done(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_done),
    .ap_idle(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_idle),
    .ap_ready(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_num_data_valid(imgRB_num_data_valid),
    .imgRB_fifo_cap(imgRB_fifo_cap),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRB_read),
    .imgRgb_din(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_din),
    .imgRgb_num_data_valid(3'd0),
    .imgRgb_fifo_cap(3'd0),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_write),
    .pixWindow_322_i(pixBuf_170_load_reg_1058),
    .pixWindow_321_i(pixBuf_169_load_reg_1053),
    .pixWindow_320_i(pixBuf_168_load_reg_1048),
    .pixWindow_325_i(pixBuf_167_load_reg_1043),
    .pixWindow_324_i(pixBuf_166_load_reg_1038),
    .pixWindow_323_i(pixBuf_165_load_reg_1033),
    .pixWindow_328_i(pixBuf_164_load_reg_1028),
    .pixWindow_327_i(pixBuf_163_load_reg_1023),
    .pixWindow_326_i(pixBuf_load_reg_1018),
    .pixWindow_208_i(pixWindow_329_load_reg_1013),
    .pixWindow_207_i(pixWindow_328_load_reg_1008),
    .pixWindow_206_i(pixWindow_327_load_reg_1003),
    .pixWindow_205_i(pixWindow_326_load_reg_998),
    .pixWindow_204_i(pixWindow_325_load_reg_993),
    .pixWindow_203_i(pixWindow_324_load_reg_988),
    .pixWindow_202_i(pixWindow_323_load_reg_983),
    .pixWindow_201_i(pixWindow_322_load_reg_978),
    .pixWindow_200_i(pixWindow_321_load_reg_973),
    .pixWindow_196_i(pixWindow_320_load_reg_968),
    .pixWindow_195_i(pixWindow_319_load_reg_963),
    .pixWindow_194_i(pixWindow_318_load_reg_958),
    .pixWindow_193_i(pixWindow_317_load_reg_953),
    .pixWindow_192_i(pixWindow_316_load_reg_948),
    .pixWindow_191_i(pixWindow_315_load_reg_943),
    .pixWindow_190_i(pixWindow_314_load_reg_938),
    .pixWindow_189_i(pixWindow_313_load_reg_933),
    .pixWindow_188_i(pixWindow_312_load_reg_928),
    .pixWindow_184_i(pixWindow_311_load_reg_923),
    .pixWindow_183_i(pixWindow_310_load_reg_918),
    .pixWindow_182_i(pixWindow_309_load_reg_913),
    .pixWindow_181_i(pixWindow_308_load_reg_908),
    .pixWindow_180_i(pixWindow_307_load_reg_903),
    .pixWindow_179_i(pixWindow_306_load_reg_898),
    .pixWindow_178_i(pixWindow_305_load_reg_893),
    .pixWindow_177_i(pixWindow_304_load_reg_888),
    .pixWindow_i(pixWindow_load_reg_883),
    .p_0_2_0_0_01168_31942_lcssa2037_i(p_0_2_0_0_01168_31942_lcssa2037_i_load_reg_878),
    .p_0_1_0_0_01167_31939_lcssa2035_i(p_0_1_0_0_01167_31939_lcssa2035_i_load_reg_873),
    .p_0_0_0_0_01166_31936_lcssa2033_i(p_0_0_0_0_01166_31936_lcssa2033_i_load_reg_868),
    .add_ln878_1_i(add_ln878_1_reg_855),
    .cmp310_i(cmp310_i_reg_1073),
    .cmp310_1_i(cmp310_1_i_reg_1078),
    .cmp478_i(cmp478_i_reg_1063),
    .lineBuffer_1_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address0),
    .lineBuffer_1_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce0),
    .lineBuffer_1_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_we0),
    .lineBuffer_1_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_d0),
    .lineBuffer_1_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_address1),
    .lineBuffer_1_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_1_i_ce1),
    .lineBuffer_1_i_q1(lineBuffer_2_q1),
    .lineBuffer_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address0),
    .lineBuffer_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce0),
    .lineBuffer_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_we0),
    .lineBuffer_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_d0),
    .lineBuffer_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_address1),
    .lineBuffer_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_lineBuffer_i_ce1),
    .lineBuffer_i_q1(lineBuffer_q1),
    .empty(width),
    .cmp59_i(cmp59_i_reg_1068),
    .pixWindow_331_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out),
    .pixWindow_331_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out_ap_vld),
    .pixWindow_330_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out),
    .pixWindow_330_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out_ap_vld),
    .pixWindow_329_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out),
    .pixWindow_329_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out_ap_vld),
    .pixWindow_334_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out),
    .pixWindow_334_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out_ap_vld),
    .pixWindow_333_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out),
    .pixWindow_333_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out_ap_vld),
    .pixWindow_332_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out),
    .pixWindow_332_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out_ap_vld),
    .pixWindow_337_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out),
    .pixWindow_337_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out_ap_vld),
    .pixWindow_336_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out),
    .pixWindow_336_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out_ap_vld),
    .pixWindow_335_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out),
    .pixWindow_335_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out_ap_vld),
    .pixWindow_244_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out),
    .pixWindow_244_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out_ap_vld),
    .pixWindow_243_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out),
    .pixWindow_243_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out_ap_vld),
    .pixWindow_242_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out),
    .pixWindow_242_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out_ap_vld),
    .pixWindow_241_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out),
    .pixWindow_241_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out_ap_vld),
    .pixWindow_240_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out),
    .pixWindow_240_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out_ap_vld),
    .pixWindow_239_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out),
    .pixWindow_239_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out_ap_vld),
    .pixWindow_238_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out),
    .pixWindow_238_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out_ap_vld),
    .pixWindow_237_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out),
    .pixWindow_237_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out_ap_vld),
    .pixWindow_236_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out),
    .pixWindow_236_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out_ap_vld),
    .pixWindow_232_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out),
    .pixWindow_232_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out_ap_vld),
    .pixWindow_231_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out),
    .pixWindow_231_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out_ap_vld),
    .pixWindow_230_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out),
    .pixWindow_230_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out_ap_vld),
    .pixWindow_229_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out),
    .pixWindow_229_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out_ap_vld),
    .pixWindow_228_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out),
    .pixWindow_228_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out_ap_vld),
    .pixWindow_227_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out),
    .pixWindow_227_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out_ap_vld),
    .pixWindow_226_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out),
    .pixWindow_226_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out_ap_vld),
    .pixWindow_225_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out),
    .pixWindow_225_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out_ap_vld),
    .pixWindow_224_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out),
    .pixWindow_224_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out_ap_vld),
    .pixWindow_220_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out),
    .pixWindow_220_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out_ap_vld),
    .pixWindow_219_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out),
    .pixWindow_219_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out_ap_vld),
    .pixWindow_218_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out),
    .pixWindow_218_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out_ap_vld),
    .pixWindow_217_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out),
    .pixWindow_217_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out_ap_vld),
    .pixWindow_216_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out),
    .pixWindow_216_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out_ap_vld),
    .pixWindow_215_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out),
    .pixWindow_215_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out_ap_vld),
    .pixWindow_214_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out),
    .pixWindow_214_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out_ap_vld),
    .pixWindow_213_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out),
    .pixWindow_213_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out_ap_vld),
    .pixWindow_212_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out),
    .pixWindow_212_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out_ap_vld),
    .p_0_2_0_0_01168_31944_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out),
    .p_0_2_0_0_01168_31944_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out_ap_vld),
    .p_0_1_0_0_01167_31941_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out),
    .p_0_1_0_0_01167_31941_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out_ap_vld),
    .p_0_0_0_0_01166_31938_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out),
    .p_0_0_0_0_01166_31938_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln878_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_ready == 1'b1)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_72 <= 10'd0;
    end else if (((icmp_ln878_fu_415_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_72 <= y_6_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((bayerPhase_c_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln878_1_reg_855 <= add_ln878_1_fu_396_p2;
        loopHeight_reg_840 <= loopHeight_fu_357_p2;
        trunc_ln870_1_i_reg_845 <= {{bayerPhase_c_dout[15:1]}};
        xor309_1_cast_i_reg_860[0] <= xor309_1_cast_i_fu_408_p1[0];
        zext_ln871_reg_850[0] <= zext_ln871_fu_377_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp310_1_i_reg_1078 <= cmp310_1_i_fu_578_p2;
        cmp310_i_reg_1073 <= cmp310_i_fu_573_p2;
        cmp478_i_reg_1063 <= cmp478_i_fu_562_p2;
        cmp59_i_reg_1068 <= cmp59_i_fu_568_p2;
        p_0_0_0_0_01166_31936_lcssa2033_i_load_reg_868 <= p_0_0_0_0_01166_31936_lcssa2033_i_fu_76;
        p_0_1_0_0_01167_31939_lcssa2035_i_load_reg_873 <= p_0_1_0_0_01167_31939_lcssa2035_i_fu_80;
        p_0_2_0_0_01168_31942_lcssa2037_i_load_reg_878 <= p_0_2_0_0_01168_31942_lcssa2037_i_fu_84;
        pixBuf_163_load_reg_1023 <= pixBuf_163_fu_200;
        pixBuf_164_load_reg_1028 <= pixBuf_164_fu_204;
        pixBuf_165_load_reg_1033 <= pixBuf_165_fu_208;
        pixBuf_166_load_reg_1038 <= pixBuf_166_fu_212;
        pixBuf_167_load_reg_1043 <= pixBuf_167_fu_216;
        pixBuf_168_load_reg_1048 <= pixBuf_168_fu_220;
        pixBuf_169_load_reg_1053 <= pixBuf_169_fu_224;
        pixBuf_170_load_reg_1058 <= pixBuf_170_fu_228;
        pixBuf_load_reg_1018 <= pixBuf_fu_196;
        pixWindow_304_load_reg_888 <= pixWindow_304_fu_92;
        pixWindow_305_load_reg_893 <= pixWindow_305_fu_96;
        pixWindow_306_load_reg_898 <= pixWindow_306_fu_100;
        pixWindow_307_load_reg_903 <= pixWindow_307_fu_104;
        pixWindow_308_load_reg_908 <= pixWindow_308_fu_108;
        pixWindow_309_load_reg_913 <= pixWindow_309_fu_112;
        pixWindow_310_load_reg_918 <= pixWindow_310_fu_116;
        pixWindow_311_load_reg_923 <= pixWindow_311_fu_120;
        pixWindow_312_load_reg_928 <= pixWindow_312_fu_124;
        pixWindow_313_load_reg_933 <= pixWindow_313_fu_128;
        pixWindow_314_load_reg_938 <= pixWindow_314_fu_132;
        pixWindow_315_load_reg_943 <= pixWindow_315_fu_136;
        pixWindow_316_load_reg_948 <= pixWindow_316_fu_140;
        pixWindow_317_load_reg_953 <= pixWindow_317_fu_144;
        pixWindow_318_load_reg_958 <= pixWindow_318_fu_148;
        pixWindow_319_load_reg_963 <= pixWindow_319_fu_152;
        pixWindow_320_load_reg_968 <= pixWindow_320_fu_156;
        pixWindow_321_load_reg_973 <= pixWindow_321_fu_160;
        pixWindow_322_load_reg_978 <= pixWindow_322_fu_164;
        pixWindow_323_load_reg_983 <= pixWindow_323_fu_168;
        pixWindow_324_load_reg_988 <= pixWindow_324_fu_172;
        pixWindow_325_load_reg_993 <= pixWindow_325_fu_176;
        pixWindow_326_load_reg_998 <= pixWindow_326_fu_180;
        pixWindow_327_load_reg_1003 <= pixWindow_327_fu_184;
        pixWindow_328_load_reg_1008 <= pixWindow_328_fu_188;
        pixWindow_329_load_reg_1013 <= pixWindow_329_fu_192;
        pixWindow_load_reg_883 <= pixWindow_fu_88;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0_0_01166_31936_lcssa2033_i_fu_76 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_0_0_0_01166_31938_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_1_0_0_01167_31939_lcssa2035_i_fu_80 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_1_0_0_01167_31941_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_2_0_0_01168_31942_lcssa2037_i_fu_84 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_p_0_2_0_0_01168_31944_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_163_fu_200 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_336_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_164_fu_204 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_337_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_165_fu_208 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_332_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_166_fu_212 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_333_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_167_fu_216 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_334_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_168_fu_220 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_329_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_169_fu_224 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_330_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_170_fu_228 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_331_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixBuf_fu_196 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_335_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_304_fu_92 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_213_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_305_fu_96 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_214_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_306_fu_100 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_215_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_307_fu_104 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_216_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_308_fu_108 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_217_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_309_fu_112 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_218_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_310_fu_116 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_219_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_311_fu_120 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_220_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_312_fu_124 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_224_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_313_fu_128 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_225_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_314_fu_132 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_226_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_315_fu_136 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_227_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_316_fu_140 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_228_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_317_fu_144 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_229_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_318_fu_148 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_230_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_319_fu_152 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_231_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_320_fu_156 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_232_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_321_fu_160 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_236_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_322_fu_164 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_237_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_323_fu_168 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_238_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_324_fu_172 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_239_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_325_fu_176 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_240_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_326_fu_180 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_241_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_327_fu_184 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_242_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_328_fu_188 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_243_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_329_fu_192 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_244_i_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pixWindow_fu_88 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_pixWindow_212_i_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((bayerPhase_c_empty_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bayerPhase_c_blk_n = bayerPhase_c_empty_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((bayerPhase_c_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        bayerPhase_c_read = 1'b1;
    end else begin
        bayerPhase_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imgRB_read = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRB_read;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        imgRgb_write = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_write;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((bayerPhase_c_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln878_fu_415_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln878_1_fu_396_p2 = (trunc_ln_i_fu_386_p4 + 8'd1);

assign add_ln878_fu_381_p2 = (width + 10'd3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp310_1_i_fu_578_p2 = ((xor_i_fu_557_p2 != xor309_1_cast_i_reg_860) ? 1'b1 : 1'b0);

assign cmp310_i_fu_573_p2 = ((xor_i_fu_557_p2 != zext_ln871_reg_850) ? 1'b1 : 1'b0);

assign cmp478_i_fu_562_p2 = ((y_fu_72 != 10'd0) ? 1'b1 : 1'b0);

assign cmp59_i_fu_568_p2 = ((y_fu_72 < height) ? 1'b1 : 1'b0);

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_ap_start_reg;

assign icmp_ln878_fu_415_p2 = ((y_fu_72 == loopHeight_reg_840) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2_fu_258_imgRgb_din;

assign loopHeight_fu_357_p2 = (height + 10'd1);

assign tmp_cast_i_fu_553_p1 = tmp_i_fu_547_p2;

assign tmp_i_fu_547_p2 = (trunc_ln878_fu_543_p1 ^ 1'd1);

assign trunc_ln878_fu_543_p1 = y_fu_72[0:0];

assign trunc_ln_i_fu_386_p4 = {{add_ln878_fu_381_p2[9:2]}};

assign x_phase_fu_363_p1 = bayerPhase_c_dout[0:0];

assign xor309_1_cast_i_fu_408_p1 = xor309_1_i_fu_402_p2;

assign xor309_1_i_fu_402_p2 = (x_phase_fu_363_p1 ^ 1'd1);

assign xor_i_fu_557_p2 = (trunc_ln870_1_i_reg_845 ^ tmp_cast_i_fu_553_p1);

assign y_6_fu_420_p2 = (y_fu_72 + 10'd1);

assign zext_ln871_fu_377_p1 = x_phase_fu_363_p1;

always @ (posedge ap_clk) begin
    zext_ln871_reg_850[14:1] <= 14'b00000000000000;
    xor309_1_cast_i_reg_860[14:1] <= 14'b00000000000000;
end

endmodule //system_v_demosaic_0_0_DebayerRandBatG
