-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_demosaic_0_0_abs_r is
port (
    ap_ready : OUT STD_LOGIC;
    p_x : IN STD_LOGIC_VECTOR (12 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of system_v_demosaic_0_0_abs_r is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal empty_fu_16_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_26_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln61_fu_20_p2 : STD_LOGIC_VECTOR (11 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        sub_ln61_fu_20_p2 when (tmp_fu_26_p3(0) = '1') else 
        empty_fu_16_p1;
    empty_fu_16_p1 <= p_x(12 - 1 downto 0);
    sub_ln61_fu_20_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(empty_fu_16_p1));
    tmp_fu_26_p3 <= p_x(12 downto 12);
end behav;
