-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_demosaic_0_0_DebayerRatBorBatR is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    imgG_dout : IN STD_LOGIC_VECTOR (119 downto 0);
    imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgG_empty_n : IN STD_LOGIC;
    imgG_read : OUT STD_LOGIC;
    imgRB_din : OUT STD_LOGIC_VECTOR (119 downto 0);
    imgRB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgRB_full_n : IN STD_LOGIC;
    imgRB_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (9 downto 0);
    width : IN STD_LOGIC_VECTOR (9 downto 0);
    bayerPhase_c9_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c9_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c9_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c9_empty_n : IN STD_LOGIC;
    bayerPhase_c9_read : OUT STD_LOGIC;
    bayerPhase_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    bayerPhase_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    bayerPhase_c_full_n : IN STD_LOGIC;
    bayerPhase_c_write : OUT STD_LOGIC );
end;


architecture behav of system_v_demosaic_0_0_DebayerRatBorBatR is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv10_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal bayerPhase_c9_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal bayerPhase_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal loopHeight_fu_388_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal loopHeight_reg_903 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln622_1_i_reg_908 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln623_fu_408_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln623_reg_914 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln630_1_fu_427_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln630_1_reg_919 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor313_1_cast_i_fu_439_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor313_1_cast_i_reg_924 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_load_reg_962 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_141_load_reg_967 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_142_load_reg_972 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_143_load_reg_977 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_144_load_reg_982 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_145_load_reg_987 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_146_load_reg_992 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_147_load_reg_997 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_148_load_reg_1002 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_149_load_reg_1007 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_150_load_reg_1012 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_151_load_reg_1017 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_152_load_reg_1022 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_153_load_reg_1027 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_154_load_reg_1032 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_155_load_reg_1037 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_156_load_reg_1042 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_157_load_reg_1047 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_158_load_reg_1052 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_159_load_reg_1057 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_160_load_reg_1062 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_161_load_reg_1067 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_162_load_reg_1072 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_163_load_reg_1077 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_164_load_reg_1082 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_165_load_reg_1087 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_166_load_reg_1092 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_load_reg_1097 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_78_load_reg_1102 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_79_load_reg_1107 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_80_load_reg_1112 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_81_load_reg_1117 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_82_load_reg_1122 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_83_load_reg_1127 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_84_load_reg_1132 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_85_load_reg_1137 : STD_LOGIC_VECTOR (9 downto 0);
    signal red_i_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal red_i_reg_1142 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp558_i_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp558_i_reg_1147 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp59_i_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp59_i_reg_1152 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp314_i_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp314_i_reg_1157 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp314_1_i_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp314_1_i_reg_1162 : STD_LOGIC_VECTOR (0 downto 0);
    signal lineBuffer_q1 : STD_LOGIC_VECTOR (119 downto 0);
    signal lineBuffer_1_q1 : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_idle : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0 : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0 : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1 : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld : STD_LOGIC;
    signal grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pixBuf_85_fu_244 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_84_fu_240 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_83_fu_236 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_82_fu_232 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_81_fu_228 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_80_fu_224 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_79_fu_220 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_78_fu_216 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixBuf_fu_212 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_166_fu_208 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_165_fu_204 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_164_fu_200 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_163_fu_196 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_162_fu_192 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_161_fu_188 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_160_fu_184 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_159_fu_180 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_158_fu_176 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_157_fu_172 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_156_fu_168 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_155_fu_164 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_154_fu_160 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_153_fu_156 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_152_fu_152 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_151_fu_148 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_150_fu_144 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_149_fu_140 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_148_fu_136 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_147_fu_132 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_146_fu_128 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_145_fu_124 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_144_fu_120 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_143_fu_116 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_142_fu_112 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_141_fu_108 : STD_LOGIC_VECTOR (9 downto 0);
    signal pixWindow_fu_104 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_0925_21699_lcssa1771_i_fu_100 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_0924_21696_lcssa1769_i_fu_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_0923_21693_lcssa1767_i_fu_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_2_0_0_0931_21633_lcssa1759_i_fu_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_0930_21630_lcssa1757_i_fu_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_0929_21627_lcssa1755_i_fu_80 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_76 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal y_4_fu_451_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln630_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_phase_fu_394_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln630_fu_412_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln_i_fu_417_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor313_1_i_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln630_fu_583_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and310_i_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and310_cast_i_fu_593_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_i_fu_597_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgG_dout : IN STD_LOGIC_VECTOR (119 downto 0);
        imgG_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgG_empty_n : IN STD_LOGIC;
        imgG_read : OUT STD_LOGIC;
        imgRB_din : OUT STD_LOGIC_VECTOR (119 downto 0);
        imgRB_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRB_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgRB_full_n : IN STD_LOGIC;
        imgRB_write : OUT STD_LOGIC;
        pixWindow_146_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_145_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_144_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_149_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_148_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_147_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_152_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_151_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_150_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_32_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_31_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_30_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_29_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_28_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_27_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_26_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_25_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_24_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_20_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_19_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_18_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_17_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_16_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_15_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_14_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_13_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_12_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_8_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_7_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_6_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_5_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_4_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_3_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_2_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_1_i : IN STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0925_21699_lcssa1771_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0924_21696_lcssa1769_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0923_21693_lcssa1767_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0931_21633_lcssa1759_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0930_21630_lcssa1757_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0929_21627_lcssa1755_i : IN STD_LOGIC_VECTOR (9 downto 0);
        add_ln630_1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp558_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp314_1_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp314_i : IN STD_LOGIC_VECTOR (0 downto 0);
        lineBuffer_1_i_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        lineBuffer_1_i_ce0 : OUT STD_LOGIC;
        lineBuffer_1_i_we0 : OUT STD_LOGIC;
        lineBuffer_1_i_d0 : OUT STD_LOGIC_VECTOR (119 downto 0);
        lineBuffer_1_i_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        lineBuffer_1_i_ce1 : OUT STD_LOGIC;
        lineBuffer_1_i_q1 : IN STD_LOGIC_VECTOR (119 downto 0);
        lineBuffer_i_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        lineBuffer_i_ce0 : OUT STD_LOGIC;
        lineBuffer_i_we0 : OUT STD_LOGIC;
        lineBuffer_i_d0 : OUT STD_LOGIC_VECTOR (119 downto 0);
        lineBuffer_i_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        lineBuffer_i_ce1 : OUT STD_LOGIC;
        lineBuffer_i_q1 : IN STD_LOGIC_VECTOR (119 downto 0);
        empty : IN STD_LOGIC_VECTOR (9 downto 0);
        cmp59_i : IN STD_LOGIC_VECTOR (0 downto 0);
        red_i : IN STD_LOGIC_VECTOR (0 downto 0);
        pixWindow_155_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_155_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_154_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_154_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_153_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_153_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_158_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_158_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_157_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_157_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_156_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_156_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_161_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_161_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_160_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_160_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_159_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_159_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_68_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_68_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_67_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_67_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_66_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_66_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_65_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_65_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_64_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_64_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_63_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_63_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_62_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_62_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_61_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_61_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_60_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_60_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_56_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_56_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_55_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_55_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_54_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_54_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_53_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_53_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_52_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_52_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_51_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_51_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_50_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_50_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_49_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_49_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_48_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_48_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_44_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_44_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_43_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_43_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_42_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_42_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_41_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_41_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_40_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_40_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_39_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_39_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_38_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_38_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_37_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_37_i_out_ap_vld : OUT STD_LOGIC;
        pixWindow_36_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        pixWindow_36_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0925_21701_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0925_21701_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0924_21698_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0924_21698_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0923_21695_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0923_21695_i_out_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0931_21635_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0931_21635_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0930_21632_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0930_21632_i_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0929_21629_i_out : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0929_21629_i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component system_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (119 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (119 downto 0) );
    end component;



begin
    lineBuffer_U : component system_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_RAM_AUTO_1R1W
    generic map (
        DataWidth => 120,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0,
        ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0,
        we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0,
        d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0,
        address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1,
        ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1,
        q1 => lineBuffer_q1);

    lineBuffer_1_U : component system_v_demosaic_0_0_DebayerRatBorBatR_lineBuffer_RAM_AUTO_1R1W
    generic map (
        DataWidth => 120,
        AddressRange => 181,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0,
        ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0,
        we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0,
        d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0,
        address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1,
        ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1,
        q1 => lineBuffer_1_q1);

    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282 : component system_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start,
        ap_done => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done,
        ap_idle => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_idle,
        ap_ready => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready,
        imgG_dout => imgG_dout,
        imgG_num_data_valid => imgG_num_data_valid,
        imgG_fifo_cap => imgG_fifo_cap,
        imgG_empty_n => imgG_empty_n,
        imgG_read => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read,
        imgRB_din => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din,
        imgRB_num_data_valid => ap_const_lv3_0,
        imgRB_fifo_cap => ap_const_lv3_0,
        imgRB_full_n => imgRB_full_n,
        imgRB_write => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write,
        pixWindow_146_i => pixBuf_85_load_reg_1137,
        pixWindow_145_i => pixBuf_84_load_reg_1132,
        pixWindow_144_i => pixBuf_83_load_reg_1127,
        pixWindow_149_i => pixBuf_82_load_reg_1122,
        pixWindow_148_i => pixBuf_81_load_reg_1117,
        pixWindow_147_i => pixBuf_80_load_reg_1112,
        pixWindow_152_i => pixBuf_79_load_reg_1107,
        pixWindow_151_i => pixBuf_78_load_reg_1102,
        pixWindow_150_i => pixBuf_load_reg_1097,
        pixWindow_32_i => pixWindow_166_load_reg_1092,
        pixWindow_31_i => pixWindow_165_load_reg_1087,
        pixWindow_30_i => pixWindow_164_load_reg_1082,
        pixWindow_29_i => pixWindow_163_load_reg_1077,
        pixWindow_28_i => pixWindow_162_load_reg_1072,
        pixWindow_27_i => pixWindow_161_load_reg_1067,
        pixWindow_26_i => pixWindow_160_load_reg_1062,
        pixWindow_25_i => pixWindow_159_load_reg_1057,
        pixWindow_24_i => pixWindow_158_load_reg_1052,
        pixWindow_20_i => pixWindow_157_load_reg_1047,
        pixWindow_19_i => pixWindow_156_load_reg_1042,
        pixWindow_18_i => pixWindow_155_load_reg_1037,
        pixWindow_17_i => pixWindow_154_load_reg_1032,
        pixWindow_16_i => pixWindow_153_load_reg_1027,
        pixWindow_15_i => pixWindow_152_load_reg_1022,
        pixWindow_14_i => pixWindow_151_load_reg_1017,
        pixWindow_13_i => pixWindow_150_load_reg_1012,
        pixWindow_12_i => pixWindow_149_load_reg_1007,
        pixWindow_8_i => pixWindow_148_load_reg_1002,
        pixWindow_7_i => pixWindow_147_load_reg_997,
        pixWindow_6_i => pixWindow_146_load_reg_992,
        pixWindow_5_i => pixWindow_145_load_reg_987,
        pixWindow_4_i => pixWindow_144_load_reg_982,
        pixWindow_3_i => pixWindow_143_load_reg_977,
        pixWindow_2_i => pixWindow_142_load_reg_972,
        pixWindow_1_i => pixWindow_141_load_reg_967,
        pixWindow_i => pixWindow_load_reg_962,
        p_0_2_0_0_0925_21699_lcssa1771_i => p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957,
        p_0_1_0_0_0924_21696_lcssa1769_i => p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952,
        p_0_0_0_0_0923_21693_lcssa1767_i => p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947,
        p_0_2_0_0_0931_21633_lcssa1759_i => p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942,
        p_0_1_0_0_0930_21630_lcssa1757_i => p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937,
        p_0_0_0_0_0929_21627_lcssa1755_i => p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932,
        add_ln630_1_i => add_ln630_1_reg_919,
        cmp558_i => cmp558_i_reg_1147,
        cmp314_1_i => cmp314_1_i_reg_1162,
        cmp314_i => cmp314_i_reg_1157,
        lineBuffer_1_i_address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address0,
        lineBuffer_1_i_ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce0,
        lineBuffer_1_i_we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_we0,
        lineBuffer_1_i_d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_d0,
        lineBuffer_1_i_address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_address1,
        lineBuffer_1_i_ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_1_i_ce1,
        lineBuffer_1_i_q1 => lineBuffer_1_q1,
        lineBuffer_i_address0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address0,
        lineBuffer_i_ce0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce0,
        lineBuffer_i_we0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_we0,
        lineBuffer_i_d0 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_d0,
        lineBuffer_i_address1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_address1,
        lineBuffer_i_ce1 => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_lineBuffer_i_ce1,
        lineBuffer_i_q1 => lineBuffer_q1,
        empty => width,
        cmp59_i => cmp59_i_reg_1152,
        red_i => red_i_reg_1142,
        pixWindow_155_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out,
        pixWindow_155_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld,
        pixWindow_154_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out,
        pixWindow_154_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld,
        pixWindow_153_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out,
        pixWindow_153_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld,
        pixWindow_158_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out,
        pixWindow_158_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld,
        pixWindow_157_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out,
        pixWindow_157_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld,
        pixWindow_156_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out,
        pixWindow_156_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld,
        pixWindow_161_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out,
        pixWindow_161_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld,
        pixWindow_160_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out,
        pixWindow_160_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld,
        pixWindow_159_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out,
        pixWindow_159_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld,
        pixWindow_68_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out,
        pixWindow_68_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld,
        pixWindow_67_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out,
        pixWindow_67_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld,
        pixWindow_66_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out,
        pixWindow_66_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld,
        pixWindow_65_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out,
        pixWindow_65_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld,
        pixWindow_64_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out,
        pixWindow_64_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld,
        pixWindow_63_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out,
        pixWindow_63_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld,
        pixWindow_62_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out,
        pixWindow_62_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld,
        pixWindow_61_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out,
        pixWindow_61_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld,
        pixWindow_60_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out,
        pixWindow_60_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld,
        pixWindow_56_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out,
        pixWindow_56_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld,
        pixWindow_55_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out,
        pixWindow_55_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld,
        pixWindow_54_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out,
        pixWindow_54_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld,
        pixWindow_53_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out,
        pixWindow_53_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld,
        pixWindow_52_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out,
        pixWindow_52_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld,
        pixWindow_51_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out,
        pixWindow_51_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld,
        pixWindow_50_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out,
        pixWindow_50_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld,
        pixWindow_49_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out,
        pixWindow_49_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld,
        pixWindow_48_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out,
        pixWindow_48_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld,
        pixWindow_44_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out,
        pixWindow_44_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld,
        pixWindow_43_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out,
        pixWindow_43_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld,
        pixWindow_42_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out,
        pixWindow_42_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld,
        pixWindow_41_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out,
        pixWindow_41_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld,
        pixWindow_40_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out,
        pixWindow_40_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld,
        pixWindow_39_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out,
        pixWindow_39_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld,
        pixWindow_38_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out,
        pixWindow_38_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld,
        pixWindow_37_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out,
        pixWindow_37_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld,
        pixWindow_36_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out,
        pixWindow_36_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld,
        p_0_2_0_0_0925_21701_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out,
        p_0_2_0_0_0925_21701_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld,
        p_0_1_0_0_0924_21698_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out,
        p_0_1_0_0_0924_21698_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld,
        p_0_0_0_0_0923_21695_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out,
        p_0_0_0_0_0923_21695_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld,
        p_0_2_0_0_0931_21635_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out,
        p_0_2_0_0_0931_21635_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld,
        p_0_1_0_0_0930_21632_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out,
        p_0_1_0_0_0930_21632_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld,
        p_0_0_0_0_0929_21629_i_out => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out,
        p_0_0_0_0_0929_21629_i_out_ap_vld => grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln630_fu_446_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_ready = ap_const_logic_1)) then 
                    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_76 <= ap_const_lv10_0;
            elsif (((icmp_ln630_fu_446_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_fu_76 <= y_4_fu_451_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln630_1_reg_919 <= add_ln630_1_fu_427_p2;
                loopHeight_reg_903 <= loopHeight_fu_388_p2;
                trunc_ln622_1_i_reg_908 <= bayerPhase_c9_dout(15 downto 1);
                    xor313_1_cast_i_reg_924(0) <= xor313_1_cast_i_fu_439_p1(0);
                    zext_ln623_reg_914(0) <= zext_ln623_fu_408_p1(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                cmp314_1_i_reg_1162 <= cmp314_1_i_fu_623_p2;
                cmp314_i_reg_1157 <= cmp314_i_fu_618_p2;
                cmp558_i_reg_1147 <= cmp558_i_fu_607_p2;
                cmp59_i_reg_1152 <= cmp59_i_fu_613_p2;
                p_0_0_0_0_0923_21693_lcssa1767_i_load_reg_947 <= p_0_0_0_0_0923_21693_lcssa1767_i_fu_92;
                p_0_0_0_0_0929_21627_lcssa1755_i_load_reg_932 <= p_0_0_0_0_0929_21627_lcssa1755_i_fu_80;
                p_0_1_0_0_0924_21696_lcssa1769_i_load_reg_952 <= p_0_1_0_0_0924_21696_lcssa1769_i_fu_96;
                p_0_1_0_0_0930_21630_lcssa1757_i_load_reg_937 <= p_0_1_0_0_0930_21630_lcssa1757_i_fu_84;
                p_0_2_0_0_0925_21699_lcssa1771_i_load_reg_957 <= p_0_2_0_0_0925_21699_lcssa1771_i_fu_100;
                p_0_2_0_0_0931_21633_lcssa1759_i_load_reg_942 <= p_0_2_0_0_0931_21633_lcssa1759_i_fu_88;
                pixBuf_78_load_reg_1102 <= pixBuf_78_fu_216;
                pixBuf_79_load_reg_1107 <= pixBuf_79_fu_220;
                pixBuf_80_load_reg_1112 <= pixBuf_80_fu_224;
                pixBuf_81_load_reg_1117 <= pixBuf_81_fu_228;
                pixBuf_82_load_reg_1122 <= pixBuf_82_fu_232;
                pixBuf_83_load_reg_1127 <= pixBuf_83_fu_236;
                pixBuf_84_load_reg_1132 <= pixBuf_84_fu_240;
                pixBuf_85_load_reg_1137 <= pixBuf_85_fu_244;
                pixBuf_load_reg_1097 <= pixBuf_fu_212;
                pixWindow_141_load_reg_967 <= pixWindow_141_fu_108;
                pixWindow_142_load_reg_972 <= pixWindow_142_fu_112;
                pixWindow_143_load_reg_977 <= pixWindow_143_fu_116;
                pixWindow_144_load_reg_982 <= pixWindow_144_fu_120;
                pixWindow_145_load_reg_987 <= pixWindow_145_fu_124;
                pixWindow_146_load_reg_992 <= pixWindow_146_fu_128;
                pixWindow_147_load_reg_997 <= pixWindow_147_fu_132;
                pixWindow_148_load_reg_1002 <= pixWindow_148_fu_136;
                pixWindow_149_load_reg_1007 <= pixWindow_149_fu_140;
                pixWindow_150_load_reg_1012 <= pixWindow_150_fu_144;
                pixWindow_151_load_reg_1017 <= pixWindow_151_fu_148;
                pixWindow_152_load_reg_1022 <= pixWindow_152_fu_152;
                pixWindow_153_load_reg_1027 <= pixWindow_153_fu_156;
                pixWindow_154_load_reg_1032 <= pixWindow_154_fu_160;
                pixWindow_155_load_reg_1037 <= pixWindow_155_fu_164;
                pixWindow_156_load_reg_1042 <= pixWindow_156_fu_168;
                pixWindow_157_load_reg_1047 <= pixWindow_157_fu_172;
                pixWindow_158_load_reg_1052 <= pixWindow_158_fu_176;
                pixWindow_159_load_reg_1057 <= pixWindow_159_fu_180;
                pixWindow_160_load_reg_1062 <= pixWindow_160_fu_184;
                pixWindow_161_load_reg_1067 <= pixWindow_161_fu_188;
                pixWindow_162_load_reg_1072 <= pixWindow_162_fu_192;
                pixWindow_163_load_reg_1077 <= pixWindow_163_fu_196;
                pixWindow_164_load_reg_1082 <= pixWindow_164_fu_200;
                pixWindow_165_load_reg_1087 <= pixWindow_165_fu_204;
                pixWindow_166_load_reg_1092 <= pixWindow_166_fu_208;
                pixWindow_load_reg_962 <= pixWindow_fu_104;
                red_i_reg_1142 <= red_i_fu_602_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_0_0_0_0923_21693_lcssa1767_i_fu_92 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0923_21695_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_0_0_0_0929_21627_lcssa1755_i_fu_80 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_0_0_0_0929_21629_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_1_0_0_0924_21696_lcssa1769_i_fu_96 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0924_21698_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_1_0_0_0930_21630_lcssa1757_i_fu_84 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_1_0_0_0930_21632_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_2_0_0_0925_21699_lcssa1771_i_fu_100 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0925_21701_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                p_0_2_0_0_0931_21633_lcssa1759_i_fu_88 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_p_0_2_0_0_0931_21635_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_78_fu_216 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_160_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_79_fu_220 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_161_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_80_fu_224 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_156_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_81_fu_228 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_157_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_82_fu_232 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_158_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_83_fu_236 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_153_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_84_fu_240 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_154_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_85_fu_244 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_155_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixBuf_fu_212 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_159_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_141_fu_108 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_37_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_142_fu_112 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_38_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_143_fu_116 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_39_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_144_fu_120 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_40_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_145_fu_124 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_41_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_146_fu_128 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_42_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_147_fu_132 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_43_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_148_fu_136 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_44_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_149_fu_140 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_48_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_150_fu_144 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_49_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_151_fu_148 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_50_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_152_fu_152 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_51_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_153_fu_156 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_52_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_154_fu_160 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_53_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_155_fu_164 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_54_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_156_fu_168 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_55_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_157_fu_172 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_56_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_158_fu_176 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_60_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_159_fu_180 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_61_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_160_fu_184 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_62_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_161_fu_188 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_63_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_162_fu_192 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_64_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_163_fu_196 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_65_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_164_fu_200 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_66_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_165_fu_204 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_67_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_166_fu_208 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_68_i_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pixWindow_fu_104 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_pixWindow_36_i_out;
            end if;
        end if;
    end process;
    zext_ln623_reg_914(14 downto 1) <= "00000000000000";
    xor313_1_cast_i_reg_924(14 downto 1) <= "00000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1, ap_block_state2, ap_CS_fsm_state3, grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done, ap_CS_fsm_state5, icmp_ln630_fu_446_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln630_fu_446_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln630_1_fu_427_p2 <= std_logic_vector(unsigned(trunc_ln_i_fu_417_p4) + unsigned(ap_const_lv8_1));
    add_ln630_fu_412_p2 <= std_logic_vector(unsigned(width) + unsigned(ap_const_lv10_3));
    and310_cast_i_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and310_i_fu_587_p2),15));
    and310_i_fu_587_p2 <= (trunc_ln630_fu_583_p1 xor ap_const_lv1_1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done)
    begin
        if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(bayerPhase_c9_empty_n, bayerPhase_c_full_n)
    begin
                ap_block_state2 <= ((bayerPhase_c_full_n = ap_const_logic_0) or (bayerPhase_c9_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln630_fu_446_p2)
    begin
        if (((icmp_ln630_fu_446_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    bayerPhase_c9_blk_n_assign_proc : process(bayerPhase_c9_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bayerPhase_c9_blk_n <= bayerPhase_c9_empty_n;
        else 
            bayerPhase_c9_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bayerPhase_c9_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            bayerPhase_c9_read <= ap_const_logic_1;
        else 
            bayerPhase_c9_read <= ap_const_logic_0;
        end if; 
    end process;


    bayerPhase_c_blk_n_assign_proc : process(bayerPhase_c_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bayerPhase_c_blk_n <= bayerPhase_c_full_n;
        else 
            bayerPhase_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bayerPhase_c_din <= bayerPhase_c9_dout;

    bayerPhase_c_write_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            bayerPhase_c_write <= ap_const_logic_1;
        else 
            bayerPhase_c_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp314_1_i_fu_623_p2 <= "1" when (xor_i_fu_597_p2 = xor313_1_cast_i_reg_924) else "0";
    cmp314_i_fu_618_p2 <= "1" when (xor_i_fu_597_p2 = zext_ln623_reg_914) else "0";
    cmp558_i_fu_607_p2 <= "0" when (y_fu_76 = ap_const_lv10_0) else "1";
    cmp59_i_fu_613_p2 <= "1" when (unsigned(y_fu_76) < unsigned(height)) else "0";
    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_ap_start_reg;
    icmp_ln630_fu_446_p2 <= "1" when (y_fu_76 = loopHeight_reg_903) else "0";

    imgG_read_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imgG_read <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgG_read;
        else 
            imgG_read <= ap_const_logic_0;
        end if; 
    end process;

    imgRB_din <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_din;

    imgRB_write_assign_proc : process(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            imgRB_write <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_fu_282_imgRB_write;
        else 
            imgRB_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln630_fu_446_p2)
    begin
        if (((icmp_ln630_fu_446_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    loopHeight_fu_388_p2 <= std_logic_vector(unsigned(height) + unsigned(ap_const_lv10_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    red_i_fu_602_p2 <= "1" when (and310_cast_i_fu_593_p1 = trunc_ln622_1_i_reg_908) else "0";
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln630_fu_583_p1 <= y_fu_76(1 - 1 downto 0);
    trunc_ln_i_fu_417_p4 <= add_ln630_fu_412_p2(9 downto 2);
    x_phase_fu_394_p1 <= bayerPhase_c9_dout(1 - 1 downto 0);
    xor313_1_cast_i_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor313_1_i_fu_433_p2),15));
    xor313_1_i_fu_433_p2 <= (x_phase_fu_394_p1 xor ap_const_lv1_1);
    xor_i_fu_597_p2 <= (trunc_ln622_1_i_reg_908 xor and310_cast_i_fu_593_p1);
    y_4_fu_451_p2 <= std_logic_vector(unsigned(y_fu_76) + unsigned(ap_const_lv10_1));
    zext_ln623_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_phase_fu_394_p1),15));
end behav;
